### ISSUE TITLE
[Bug] Error in documentation

### ISSUE THREAD

**Issue by ElijahSink** [creativetimofficial/now-ui-dashboard-react#10]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/now-ui-dashboard-react/#/documentation/alerts
### Operating System
N/A
### Device
N/A
### Browser & Version
N/A
### Steps to reproduce
Navigate to https://demos.creative-tim.com/now-ui-dashboard-react/#/documentation/alerts
### What is expected?
Each alert type should have a different name:
primary, secondary, success, etc.
### What is actually happening?
Each alert has the same name (primary), although the colors are correct.

---
### Solution
Fix the names of the alerts.

**Comment by EINazare** [comment]
Hello there, @ElijahSink ,

Thank you for your interest in working with our products and for noticing this issue.
I'll make an update later this week. Please leave this issue open until then.

Best,
Manu
