### ISSUE TITLE
[Bug] Only 7 Components in Pro version

### ISSUE THREAD

**Issue by Pt4r** [creativetimofficial/now-ui-dashboard-react#11]
### Version
1.2.0
### Reproduction link
https://github.com/Pt4r
### Operating System
WIndows 10
### Device
PC
### Browser & Version
Firefox
### Steps to reproduce
Just download it
### What is expected?
To get 169 comps as described
### What is actually happening?
I get only 7

---

**Comment by EINazare** [comment]
Hi, @Pt4r 

Thank you for your interest in working with our products. In our product on the http://demos.creative-tim.com/material-kit-pro/index.html you will find those components, but in some way to calculate all the components that are present in the product you have to take in consideration, for example, all the classes for the buttons that modify the color, sizes or style of the components. Approximately every component that you will find in the index.html like buttons, inputs, navbars, tables, nav-pills, switches, comments, modals and so on ( see all the index.html page ) have these classes options that modify their color or size or appearance and also we produced more components in the http://demos.creative-tim.com/material-kit-pro/sections.html#headers and every example page from the components that are present in the index.html page.

Hope these informations will help you! Just let us know if we can give any other information.

Regards, Manu
