### ISSUE TITLE
[Bug] CSS Sourcemaps not working

### ISSUE THREAD

**Issue by jarkin13** [creativetimofficial/now-ui-dashboard-react#12]
### Version
1.2
### Reproduction link
https://github.com/creativetimofficial/now-ui-dashboard-react
### Operating System
10.15.2 - Catalina
### Device
Mac
### Browser & Version
Chrome 10.15.2
### Steps to reproduce
npm start
go to localhost:3000
inspect element
CSS only shows the inline styling
### What is expected?
In inspect element you should see the styling and what scss file it originates from
### What is actually happening?
it's displaying as inline styling in inspect element

---

**Comment by EINazare** [comment]
Hello there, @jarkin13 ,

Thank you for your interest in working with our products.
Please refer to this issue here: https://github.com/facebook/create-react-app/issues/5707

Best,
Manu
