### ISSUE TITLE
Sidebar overflow

### ISSUE THREAD

**Issue by Madm0x** [creativetimofficial/now-ui-dashboard-react#4]
There is a little issue with the sidebar when opened on mobile devices, i can't figure it out why it overflow on the bottom.

otherwise thank you for this template :)

**Comment by EINazare** [comment]
Hello @Madm0x ,

And thank you for your interest in using our product.
Can you please provide a screenshot with the problem?

Best,
Manu

**Comment by Madm0x** [comment]
![image](https://user-images.githubusercontent.com/24223170/44392305-cad50380-a529-11e8-8a3d-8dbf0c7f1723.png)

this from your own demo, same result on real device

**Comment by EINazare** [comment]
Hello @Madm0x ,

Thank you for providing this.
We are going to fix it in our next update.

Best,
Manu
