### ISSUE TITLE
How to prefill forms with data.

### ISSUE THREAD

**Issue by ashoksahoo** [creativetimofficial/now-ui-dashboard-react#5]
the form data will not change if used like this.

`{
                            label: "New Name",
                            inputProps: {
                              type: "text",
                              name: "name",
                              required: true,
                              value: this.state.old_name
                            }
                          },`

**Comment by EINazare** [comment]
Hello there @ashoksahoo ,

Thank you for your interest in working with our products.
I believe this is from React. You cannot use `value` prop. You need to use `defaultValue` prop instead.

Best,
Manu
