### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by kunaljaypatel** [creativetimofficial/now-ui-dashboard-react#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The Modal appears in the correct location on every presentation.

# Current Behavior

Sometimes the Modal does not appear in the correct location.
(https://imgur.com/a/53GNcAr)

# Failure Information (for bugs)

The Modal in Now-Ui-Dashboard-react is buggy on Safari. A portion of it sometimes gets cut off in the Safari Browser on presentation. 

## Steps to Reproduce

Use Safari Browser.
1. Navigate to the premade Notifications page.
2. Click "Notice Modal", then click "small alert modal". Keep clicking, opening, and repeating this process until you notice that one of the modals doesn't appear properly and gets stuck while cut off. 

## Context

Occurs on Safari. The code is the default code that comes with the latest version of Now-UI Dashboard Pro React. 

* Device: Macbook
* Operating System: Mac OS Mojave
* Browser and Version: Safari Version 12.0.1

## Failure Logs

N/A

**Comment by EINazare** [comment]
Hello there @kunaljaypatel ,

Thank you for your interest in working with our product.
Are you sure you have opened this issue on the right repository?
Because I am 100% sure that in our Now UI Dashboard React product we do not have Modals.
Why have you opened this issue here and not on the right repository?
How did you end up here?

Best,
Manu

**Comment by kunaljaypatel** [comment]
Hi  @ein

**Comment by kunaljaypatel** [comment]
Sorry. I didn’t realize that you distinguished between the pro version and the regular version on github. I will file this in the correct place.

**Comment by kunaljaypatel** [comment]
I have [filed it in the correct place](https://github.com/creativetimofficial/ct-now-ui-dashboard-pro-react/issues/17). Also, your [readme.md on GitHub](https://github.com/creativetimofficial/ct-now-ui-dashboard-pro-react) for Now-UI-Dashboard-Pro-React's title is "Material Dashboard PRO React".
