### ISSUE TITLE
Mobile navigation is not smooth

### ISSUE THREAD

**Issue by cesar3030** [creativetimofficial/now-ui-dashboard-react#7]
I just wanted to start with a big thanks to you guys. I love your work, your themes look amazing!

# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I expect the page scrolling **on mobile** (it works perfectly on my macbook pro) to be like other websites. If I give an impulsion towards the bottom/top of my screen with my finger, I want the page to scroll up/down smoothly, loose speed as it goes up/down and stop by itself.  

# Current Behavior
What is the current behavior?

To scroll up/down I need to keep the finger on the screen and drag it up/down. As soon as I remove the finger from the screen, the scrolling stops.
I checked other of your React themes with my mobile and they work properly. This issue seems to be only with this theme

# Failure Information (for bugs)
## Steps to Reproduce

With a mobile:
1. Go to the now-ui-dashboard theme: [link](https://demos.creative-tim.com/now-ui-dashboard-react/?_ga=2.125615882.1414245755.1544418192-1414445845.1544418192#/dashboard) 
2. Try to scroll up or down 
3. Go to a working theme: [black dashboard react](https://demos.creative-tim.com/black-dashboard-react/?_ga=2.102199235.334682268.1544414261-1340844505.1543623306#/admin/dashboard)
4. Try to scroll up or down and see the difference 

## Context
* Device: iPhone 7
* Operating System: iOS 12.1.1
* Browser and Version: Chrome (latest version) & Safari (latest version)

**Comment by EINazare** [comment]
Hello there @cesar3030 ,

Thank you for your interest in working with our products.
I thought that this issue was solved in the last update.
To solve it go inside `src/assets/scss/now-ui-dashboard/_sidebar-and-main-panel.scss` and at the end of the file add the following lines:

```
.sidebar,
.main-panel,
.sidebar-wrapper{
  -webkit-overflow-scrolling: touch;
}
```

Hope this information was of help.

Best,
Manu

**Comment by cesar3030** [comment]
Hi Manu!

Awesome, this fixed my issue. Thanks for your help.

Have good day!
