### ISSUE TITLE
Top navigation slideout does not close on submenu click

### ISSUE THREAD

**Issue by plamenh** [creativetimofficial/now-ui-dashboard-react#8]
When clicking on the 3-dot menu slideout (top), I would expect for this slideout to close when I click on any of the items contained inside (it is navigation, so if I click somewhere, I want to go there and not have the menu still block half my viewport). The same issue is on the pro version. 

Any idea how to fix this? Firing toggle() will not work as we want this only on small screens (below the 3-dot menu breakpoint).

Thanks.

**Comment by EINazare** [comment]
This issue was closed due to the fact that it did not comply with our [ISSUES_TEMPLATE](https://github.com/creativetimofficial/now-ui-dashboard-react/blob/master/ISSUE_TEMPLATE.md).
